#!/bin/bash

# dune-update
#
# David Adams
# August 2015
#
# Update workdir/srcs/CMakeLists.txt.
# E.g. when new packages are added or removed.

# DUNE setup.
source $DUNE_INSDIR/duneinit.sh

echo $DUNE_LINE
cd $DUNE_DEVDIR/workdir
echo Setting up $DUNE_PROJECT
setup $DUNE_PROJECT $DUNE_PROJECTVERSION -q $DUNE_QUAL

echo $DUNE_LINE
cd $DUNE_DEVDIR/workdir
echo Setting up local products
source localProducts_$DUNE_PRODUCT/setup

echo $DUNE_LINE
cd $MRB_BUILDDIR
echo Building in `pwd`
if [ -n "$DUNE_VERBOSE" ]; then echo Running mrbsetenv; fi
COM="mrb uc"
$COM 
echo "$COM" >> $DUNE_HISTORY

if [ -n "$DUNE_VERBOSE" ]; then echo exiting dune-update; fi
