#!/bin/bash

# dune-runscript
# Create setup file for running.

RUNSCRIPT=$DUNE_DEVDIR/run.sh
if [ ! -r $RUNSCRIPT ]; then
  echo "# Generated $(date)"
  echo "source $DUNE_INSDIR/duneinit.sh" >>$RUNSCRIPT
  echo export DUNE_INSDIR=$DUNE_INSDIR >>$RUNSCRIPT
  echo export DUNE_DEVDIR=$DUNE_DEVDIR >>$RUNSCRIPT
  echo 'setup $DUNE_PROJECT $DUNE_PROJECTVERSION -q $DUNE_QUAL' >>$RUNSCRIPT
  for SETUP in $DUNE_DEVDIR/workdir/localProducts*/setup; do
    echo source $SETUP >>$RUNSCRIPT
  done
  echo mrbslp >>$RUNSCRIPT
  echo "PS1=\"dune-dev> \"" >>$RUNSCRIPT
  echo "export DUNE_SHELLSCRIPT=$RUNSCRIPT" >>$RUNSCRIPT
fi
