#!/bin/bash

# dune-fastclean
#
# David Adams
# September 2015
#
# Remove local build and product areas.
# This is a quick way to start the build from scratch.
# The checked-out sources are not touched.

# DUNE setup.
source $DUNE_INSDIR/duneinit.sh

RMFILES="$DUNE_DEVDIR/workdir/localProducts_* $DUNE_DEVDIR/workdir/build_*"
# Following is a bad idea. Mrb will rebuild this file with other things in srcs.
#RMFILES="$RMFILES $DUNE_DEVDIR/workdir/srcs/CMakeLists.txt"
RMFILES="$RMFILES $DUNE_DEVDIR/run.sh"

echo Cleaning
COM="rm -rf $RMFILES"
if [ -n "$DUNE_VERBOSE" ]; then echo Running $COM; fi
$COM 
echo "$COM" >> $DUNE_HISTORY
