#!/bin/bash

# dune-build
#
# David Adams
# July 2014
#
# Build the checked-out code.

# DUNE setup.
COM="source $DUNE_INSDIR/duneinit.sh"
$COM
echo "$COM" >> $DUNE_HISTORY

echo $DUNE_LINE
COM="cd $DUNE_DEVDIR/workdir"
$COM
echo "$COM" >> $DUNE_HISTORY

echo Setting up $DUNE_PROJECT
COM="setup $DUNE_PROJECT $DUNE_PROJECTVERSION -q $DUNE_QUAL"
$COM
echo "$COM" >> $DUNE_HISTORY

echo $DUNE_LINE
LPRODDIR=localProducts_$DUNE_PRODUCT
if [ ! -r $LPRODDIR ]; then
  echo Local product directory not found:
  echo "  `pwd`/$LPRODDIR"
  echo "Run dune checkout to (re)create it"
  exit 1
fi
echo Setting up local product
COM="source $LPRODDIR/setup"
$COM
echo "$COM" >> $DUNE_HISTORY

echo $DUNE_LINE
if [ -z "$MRB_BUILDDIR" ]; then
  echo MRB_BUILDDIR must be defined.
  exit 1
fi
COM="cd $MRB_BUILDDIR"
$COM 
echo "$COM" >> $DUNE_HISTORY
echo Building in `pwd`
echo $DUNE_LINE
if [ -n "$DUNE_VERBOSE" ]; then echo Running mrbsetenv; fi
COM=mrbsetenv
$COM 
echo "$COM" >> $DUNE_HISTORY

echo $DUNE_LINE
COM="mrb i"
if [ -n "$DUNE_MAXPROC" -a $DUNE_MAXPROC -gt 1 ]; then
  COM="$COM -j$DUNE_MAXPROC"
fi
if [ -n "$DUNE_VERBOSE" ]; then echo Running $COM; fi
$COM 2>&1 | tee $DUNE_DEVDIR/build.log
echo "$COM" >> $DUNE_HISTORY

echo $DUNE_LINE
echo Set up to run
if [ -n "$DUNE_VERBOSE" ]; then echo Running mrbslp; fi
COM=mrbslp
$COM 
echo "$COM" >> $DUNE_HISTORY

echo $DUNE_LINE
echo install run script
COM="$DUNE_INSDIR/dune runscript"
$COM 
echo "$COM" >> $DUNE_HISTORY

COM="cd $THISDIR"
$COM 
echo "$COM" >> $DUNE_HISTORY

if [ -n "$DUNE_VERBOSE" ]; then echo exiting dune-build; fi
echo Build finished `date`
