#!/bin/bash

# dune-checkout
#
# David Adams
# August 2015
#
# Check out the development packages.

# DUNE setup.
source $DUNE_INSDIR/duneinit.sh

PRE="dune-checkout: "

PKGFILE=$DUNE_DEVDIR/packages.txt
if ! test -r $PKGFILE; then
  echo ${PRE}Package file not found: $PKGFILE
  exit 1
fi

# Create working area if needed.
HAVE_WORKDIR=`ls -d $DUNE_DEVDIR/workdir 2>/dev/null`
NEED_NEWDEV=
NEED_CMAKE=
echo ${PRE}$DUNE_LINE
if [ -z "$HAVE_WORKDIR" ]; then
  echo ${PRE}Creating new workdir
  COM="mkdir $DUNE_DEVDIR/workdir"
  $COM
  echo ${PRE}"$COM" >> $DUNE_HISTORY
  NEED_NEWDEV=1
else
  echo ${PRE}Using existing workdir
fi

cd $DUNE_DEVDIR/workdir

NEWDEVOPTS=
LPRODDIR=localProducts_$DUNE_PRODUCT
echo ${PRE}Local products dir is $LPRODDIR
if [ ! -r srcs ]; then
  NEED_NEWDEV=1
else if [ ! -r srcs/CMakeLists.txt ]; then
  NEED_NEWDEV=1
  NEED_CMAKE=1
  NEWDEVOPTS="-f"   # To regenerate the cmake file
else
  if [ ! -r $LPRODDIR ]; then
    NEED_NEWDEV=1
    NEWDEVOPTS="-f"   # To allow use of existing srcs area
  fi
fi; fi

echo ${PRE}$DUNE_LINE
echo ${PRE}Setting up $DUNE_PROJECT
COM="setup $DUNE_PROJECT $DUNE_PROJECTVERSION -q $DUNE_QUAL"
if ! $COM; then
  echo ${PRE}Setup failed:
  echo ${PRE}"  $COM"
  exit 1
fi
echo ${PRE}"$COM" >> $DUNE_HISTORY

if [ -n "$NEED_NEWDEV" ]; then
  echo ${PRE}$DUNE_LINE
  echo ${PRE}Creating mrb area
  if [ -n "$NEED_CMAKE" ]; then
    set -x
    mv srcs ../srcs.save
    echo ${PRE}"Checking out temporary copy of packages to force rebuild of cmake file."
    mrb newDev
    rm -rf srcs
    mv ../srcs.save srcs
    set +x
  else
    COM="mrb newDev $NEWDEVOPTS"
    $COM
    echo ${PRE}"$COM" >> $DUNE_HISTORY
  fi
  echo ${PRE}MRB_BUILDIR = $MRB_BUILDDIR
  # Update the master CMakeLists.txt file
  #COM="mrb updateDepsCM"
  #$COM
  #echo ${PRE}"$COM" >> $DUNE_HISTORY
fi

echo ${PRE}$DUNE_LINE
COM="cd $DUNE_DEVDIR/workdir"
$COM
echo "${PRE}$COM" >> $DUNE_HISTORY
echo ${PRE}Setting up local product
COM="source $LPRODDIR/setup"
$COM
echo ${PRE}"$COM" >> $DUNE_HISTORY

if ! cd srcs; then
  echo ${PRE}Unable to find workdir/srcs
  echo ${PRE}PWD is `pwd`
  exit 1
fi

# Loop over local packages and check out if not already present.
echo ${PRE}$DUNE_LINE
echo ${PRE}Checking out packages
PKGTAGS=`cat $PKGFILE | sed 's/#.*//g'`
for PKGTAG in $PKGTAGS; do
  echo ${PRE}$DUNE_LINE
  # PKGTAG = PKG or PKG%TAG
  PKG=`echo $PKGTAG | awk -F% '{print $1}'`
  TAG=`echo $PKGTAG | awk -F% '{print $2}'`
  EXTRA=`echo $PKGTAG | awk -F% '{print $3}'`
  if [ -n "$EXTRA" ]; then
    echo ${PRE}Unexpected package%tag: $PKGTAG
    exit 1
  fi
  PKGPREFIX=`echo $PKG | awk -F/ '{print $1}'`
  PKGBASE=`basename $PKG`
  if test -r $PKGBASE; then
    echo ${PRE}Package $PKG is already checked out
  else
    echo ${PRE}Checking out $PKG $TAG
    TAGSUF=
    if [ -n "$TAG" ]; then
      TAGSUF="-t $TAG"
    fi
    COM="mrb gitCheckout $TAGSUF $PKG"
    #if ! mrb gitCheckout $TAGSUF $PKG; then
    if ! $COM; then
      echo ${PRE}Checkout failed for $TAGSUF $PKG
      echo ${PRE}Command: $COM
      if echo $PKG | grep ^ssh://git >/dev/null 2>&1; then 
        echo ${PRE}Unable to gain ssh access to github.
        echo ${PRE}Test ssh access with
        echo ${PRE}"   ssh -T git@github.com"
        echo ${PRE}If that fails, add your key to the ssh agent:
        echo ${PRE}"  ssh-add ~/.ssh/github_rsa"
        echo ${PRE}"If that fails, start ssh agent with:"
        echo ${PRE}"  eval \"$(ssh-agent -s)\""
        echo ${PRE}"Or switch to http."
      else if echo $PKG | grep ^ssh://.*@cdcvs.fnal.gov >/dev/null 2>&1; then
        echo ${PRE}Unable to gain ssh access to fnal cdcvs.
        echo ${PRE}Obtain FNAL kerberos ticket.
        echo ${PRE}Or switch to http.
      else
        echo ${PRE}Unknown repository/site: $PKG
      fi; fi
      exit 1
    else
      echo $COM >> $DUNE_HISTORY
    fi
    STAT=$?
    #cd $PKGBASE
    #echo ${PRE}Create local feature branch
    #echo ${PRE}$DUNE_LINE
    #tmp git flow feature start $GIT_BRANCH_NAME
    #cd ..
  fi
  # Check if there is a platform-dependent product_deps.
  LONGPLAT=`ups flavor`
  SHORTPLAT=unknown
  if [ $LONGPLAT = "Linux64bit+2.6-2.12" ]; then SHORTPLAT=slf6; fi
  if [ $LONGPLAT = "Darwin64bit+14.5.0" ];  then SHORTPLAT=d14;  fi
  OLDDEPS=$PKGBASE/ups/product_deps
  NEWDEPS=$OLDDEPS.$SHORTPLAT
  if [ $DUNE_VERBOSE -gt 1 ]; then
    echo ${PRE}Checking for platform-dependent product_deps.
    echo ${PRE}pwd: `pwd`
    echo ${PRE}Old product deps: $OLDDEPS
    echo ${PRE}New product deps: $OLDDEPS
  fi
  if [ -r $NEWDEPS ]; then
    echo ${PRE}Using platform-dependent product_deps: $NEWDEPS
    if [ -r $OLDDEPS ]; then
      if diff $NEWDEPS $OLDDEPS 1>/dev/null; then
        if [ $DUNE_VERBOSE -gt 0 ]; then
          echo ${PRE}Exiting product_deps already matches.
        fi
      else
        cp $NEWDEPS $OLDDEPS
        echo ${PRE}New product deps installed.
      fi
    fi
  fi
done
echo ${PRE}$DUNE_LINE

# Fix the versions in local products to correspond to check outs.
# See https://cdcvs.fnal.gov/redmine/projects/lbnecode/wiki/_Tutorial_#When-a-new-LArSoft-release-is-available-and-you-want-to-develop-against-the-new-LArSoft-release.
if [ -n "$MRB_TOP" ]; then
  COM="cd $MRB_TOP"
  $COM
  echo "$COM" >> $DUNE_HISTORY
  if [ -r $LPRODDIR ]; then
    if [ -n "$DUNE_VERBOSE" ]; then echo ${PRE}Removing $LPRODDIR; fi
    rm -rf $LPRODDIR
  fi
  if [ -n "$DUNE_VERBOSE" ]; then echo ${PRE}Running mrb newDev; fi
  COM="mrb newDev -p"
  $COM
  echo "$COM" >> $DUNE_HISTORY
else
  echo ${PRE}MRB_TOP is not defined
  exit 1
fi

# Make sure the master CMakeLists.txt is up to date.
# User may have added new packages.
COM="mrb uc"
$COM
echo "$COM" >> $DUNE_HISTORY

echo ${PRE}$DUNE_LINE
exit 5

echo ${PRE}$DUNE_LINE
echo ${PRE}Set up to run
if [ -n "$DUNE_VERBOSE" ]; then echo ${PRE}Running mrbslp; fi
mrbslp
cd $THISDIR

echo ${PRE}
echo ${PRE}Generate an event: lar -n 10 -c prodsingle_lbne35t.fcl
echo ${PRE}Event display: lar -c evd_lbne35t.fcl single35t_gen.root
echo ${PRE}$DUNE_LINE
